In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [3]:
arr2 = np.zeros((2, 3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
arr3 = np.zeros((2, 3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr4 = np.ones((2, 3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arr5 = np.arange(0, 10, 2) 
arr5

array([0, 2, 4, 6, 8])

In [7]:
arr6 = np.linspace(0, 10, 5) 
arr6

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
arr7 = np.random.rand(3, 2) #(3,2) is number of rows and columns
#generates random number between 0 and 1
arr7

array([[0.25056932, 0.44363636],
       [0.28761186, 0.29100057],
       [0.36293983, 0.88872033]])

In [9]:
arr8 = np.random.randint(2,3) 
arr8

2

In [10]:
#arr1=[1,2,3]
arr1.shape

(3,)

In [24]:
arr1.ndim

1

In [28]:
arr1.size


3

In [32]:
arr1.dtype

dtype('int32')

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6])
newshape = arr.reshape(2, 3) 
newshape


array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr = np.transpose(arr)
arr

array([1, 2, 3, 4, 5, 6])

In [42]:
one = np.array([1, 2, 3])
two = np.array([4, 5, 6])
addfunc = np.add(one, two)  
subfunc= np.subtract(one,two)
multfunc= np.multiply(one,two)
divfunc= np.divide(one,two)
powfunc=np.power(one,two)

In [46]:
print(addfunc)
print(subfunc)
print(multfunc)
print(divfunc)
print(powfunc)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [50]:
np.mean(arr)

3.5

In [52]:
np.median(arr)

3.5

In [99]:
from scipy import stats
arr = np.array([4,4,4,9,9,9,3,3,2,1])
res = stats.mode(arr)
res

#basically it sorts the array first and then the most frequently occurred sorted element is given as mode. (here 4 < 9)

ModeResult(mode=4, count=3)

In [101]:
np.min(arr)


1

In [56]:
np.max(arr)


6

In [82]:
arr = np.array([1,23,45,60,10])
print(arr[2])

45


In [84]:
print(arr[1:4])

[23 45 60]


In [86]:
arr = np.array([3, 1, 2])
sorted_arr = np.sort(arr)

In [88]:
sorted_arr

array([1, 2, 3])

In [92]:
print(arr)
print(np.argmax(arr))  #index of max elem

[3 1 2]
0


In [94]:
np.argmin(arr) #index of min elem

1